### ISSUE TITLE
Microsoft Edge: Object doesn't support property or method 'Symbol(Symbol.iterator)'

### ISSUE THREAD

**Issue by ibc** [wwayne/react-tooltip#328]
My React app generates a JS bundle with browserify+babel (presets "react" and "es2015", and plugins "transform-runtime", "transform-object-assign" and "transform-object-rest-spread"), and it includes  `react-tooltip`.

When in Microsoft Edge 15, I get this error when the `<Tooltip>` component is "rendered":

```
Object doesn't support property or method 'Symbol(Symbol.iterator)'
```

I know that there are some issues with Babel + Symbol and that, sometimes, a Babel polyfill is required (I don't use polyfills in my app but just Babel runtime transformations as listed above). However, Edge does natively support `Symbol`. I mean: `typeof Symbol() === "symbol"` and so on.

So no idea about the origin of this error. However it just happens when using `react-tooltip`.

The error stack points to here (look for "// HERE"):

```js
exports.default = function (target) {
  target.prototype.bindRemovalTracker = function () {
    var _this = this;

    var MutationObserver = getMutationObserverClass();
    if (MutationObserver == null) return;

    var observer = new MutationObserver(function (mutations) {
      var _iteratorNormalCompletion = true;
      var _didIteratorError = false;
      var _iteratorError = undefined;

      try {
        for (var _iterator = mutations[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
          var mutation = _step.value;
          var _iteratorNormalCompletion2 = true;
          var _didIteratorError2 = false;
          var _iteratorError2 = undefined;

          try {
            for (var _iterator2 = mutation.removedNodes[Symbol.iterator](), _step2; !(_iteratorNormalCompletion2 = (_step2 = _iterator2.next()).done); _iteratorNormalCompletion2 = true) {
              var element = _step2.value;

              if (element === _this.state.currentTarget) {
                _this.hideTooltip();
                return;
              }
            }
          } catch (err) {
            _didIteratorError2 = true;
            _iteratorError2 = err;
          } finally {
            try {
              if (!_iteratorNormalCompletion2 && _iterator2.return) {
                _iterator2.return();
              }
            } finally {
              if (_didIteratorError2) {
                throw _iteratorError2;
              }
            }
          }
        }
      } catch (err) {
        _didIteratorError = true;
        _iteratorError = err;
      } finally {
        try {
          if (!_iteratorNormalCompletion && _iterator.return) {
            _iterator.return();
          }
        } finally {
          if (_didIteratorError) {
            throw _iteratorError;  // HERE
          }
        }
      }
    });

    observer.observe(window.document, { childList: true, subtree: true });

    this.removalTracker = observer;
  };

  target.prototype.unbindRemovalTracker = function () {
    if (this.removalTracker) {
      this.removalTracker.disconnect();
      this.removalTracker = null;
    }
  };
};
```

**Comment by ibc** [comment]
Friendly ping.

**Comment by petrogad** [comment]
I'm seeing this pretty consistently too.  Any planned fix?

**Comment by vladimirivanoviliev** [comment]
Same issue here.

**Comment by januszhou** [comment]
+1

**Comment by mvehar** [comment]
+1

**Comment by nik-lampe** [comment]
+1

**Comment by mvehar** [comment]
Quick solution:

```
// Pollyfill for Edge - react tooltip
NodeList.prototype[Symbol.iterator] = [][Symbol.iterator]
```

**Comment by pemasora** [comment]
+1, same problem

**Comment by pemasora** [comment]
How to use that quick solution? That error is breaking some javascript on IE

**Comment by danielearwicker** [comment]
IE 11 broken by this also, as it doesn't even have `Symbol`. Going to try including the source in my own project.

**Comment by ibc** [comment]
Guys, as the README clearly states this project is looking for maintainers:

> I learnt a lot from creating and maintaining react-toolip, but now I start putting my focus on other challenges, so just let me know by sending email to wayne.wang0821@gmail.com if you have interests in maintaining the project :)

So it's expected that the author won't fix this. If someone has the knowledge and the will to maintain this project, please contact him.

I do know that adding `+1` in the issue comments is much easier than taking the work with you and solving problems, but this is what we have.

**Comment by kristiankeane** [comment]
I fixed this by replacing

`for (const mutation of mutations) {
  for (const element of mutation.removedNodes) {`

with the loop equivalent:

`for (var m1 = 0; m1 < mutations.length; m1++) {
        const mutation = mutations[m1]
        for (var m2 = 0; m2 < mutation.removedNodes.length; m2++) {
          const element = mutation.removedNodes[m2]`

Make this substitution in src/decorators/trackRemoval.js and rebuild.

**Comment by pranavq212** [comment]
I am version 3.4.0, still broken on IE 11. Error is `Symbol is undfined` at `for (var _iterator = mutations[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {`

**Comment by pranavq212** [comment]
**Resolution** to this issue for IE 11 for me is to install `polyfill `which can make babel to compile `Symbol`

1. Install` babel-polyfill`
`npm install --save babel-polyfill`

2. Import `babel-polyfill` before react-tooltip
`import "babel-polyfill";`

If you are not using npm then you can use cdn to add polyfill js like:

`<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js">`

**Comment by aronhelser** [comment]
@kristiankeane I adopted your solution of simply using a 'for' loop.

Everyone who has the opportunity, please try this again with v3.4.2, and re-open if needed.
