### ISSUE TITLE
Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by marina-marina** [wwayne/react-tooltip#49]
Installed the tooltip with the standard settings from the example.  Using latest Chrome.
```<p data-tip="hello world">Tooltip</p>
        <ReactTooltip />```

 Getting `Uncaught RangeError: Maximum call stack size exceededdefineProperty `.

No issue is present it we have `effect="solid"`.

**Comment by wwayne** [comment]
When react-tooltip try to keep itself always inside the window, it may caused a endless loop bug.
Just fixed in 0.8.5.

**Comment by marina-marina** [comment]
Thank you very much.

**Comment by enjalot** [comment]
I've opened a PR to fix this more thoroughly as I ran into the problem still using `data-effect="float"` for an icon placed in the top left corner of the screen.
https://github.com/wwayne/react-tooltip/pull/68
