### ISSUE TITLE
Example Site Link is Broken

### ISSUE THREAD

**Issue by eli-crow** [wwayne/react-tooltip#549]
Example site link is broken. Thanks for this library!

**Comment by aronhelser** [comment]
@Rogger794 the easiest thing may be to use github pages, which would point to http://wwayne.github.io/react-tooltip/ I believe, but it doesn't seem to be set up.
@wwayne I think we need to turn it on in `settings`, can you do that or give one of us access?

**Comment by aronhelser** [comment]
We already have a gh-pages branch, which contains something :smile:

**Comment by Rogger794** [comment]
@aronhelser I would add a codesandbox link for that, maybe that could be a good option.

**Comment by Rogger794** [comment]
@eli-crow please, check the demo part https://www.npmjs.com/package/react-tooltip

**Comment by wwayne** [comment]
Hi @aronhelser , the demo page is being hosted by Netlify, and Netlify is using the `dist` folder of the branch `gh-pages` to set up the demo website.

But since the updates in 2020.1.31, the `dist` folder has been deleted which broke the demo site, do you know how we get back the `dist` folder? Thanks.

You can refer the commit history of the branch gh-pages [here](https://github.com/wwayne/react-tooltip/commits/gh-pages)

**Comment by aronhelser** [comment]
yes, so the gh-pages is being updated automatically by CI - on every commit to master (merge commits) the travis commands run, and push the newest changes to gh-pages. @Rogger794 's changes to the build system mean the demo site is not built the same way, so the travis commands need to be updated. Rogger, can you take a look at it? The contents of the 'public' folder in gh-pages is not a complete demo site....

**Comment by Rogger794** [comment]
@aronhelser I would check it.

**Comment by Rogger794** [comment]
@eli-crow, there is a link for Github page in the readme now, should be working.

**Comment by gregfenton** [comment]
The "example" link on the README page is still not working:

> Check example: [React-tooltip Test](https://react-tooltip.netlify.com/)

Since the github and codesandbox links are working, maybe just remove the link to the netlify example site from the README?
